### ISSUE TITLE
resque_utils not listed on Resque's plugins wiki page, or Capistrano's

### ISSUE THREAD

**Issue by leehambley** [forward3d/resque_utils#1]
I stumbled upon this via @andrew's blog, maybe you should link it on:
- https://github.com/defunkt/resque/wiki/plugins
- https://github.com/capistrano/capistrano/wiki#3rd-party-extensions

I'd do it myself, except it's possible you have intentionally not done this yourselves (too alpha/beta?)

**Comment by andrew** [comment]
We only released it a few days ago, just have not got round to promoting it yet, you're welcome to add it those pages.

**Comment by antoniogarrote** [comment]
Andrew saw it first. Thanks for the notice Lee.

**Comment by andrew** [comment]
I've just added them.
